# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\r\")\n\x0cUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"\x1a\n\x0cUsersRequest\x12\n\n\x02id\x18\x01 \x03(\r\"*\n\rUsersResponse\x12\x19\n\x04user\x18\x01 \x03(\x0b\x32\x0b.users.User\"\x14\n\x12UsersRequestStream\"0\n\x13UsersResponseStream\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User2\xba\x01\n\x05Users\x12\x32\n\x07GetUser\x12\x12.users.UserRequest\x1a\x13.users.UserResponse\x12\x35\n\x08GetUsers\x12\x13.users.UsersRequest\x1a\x14.users.UsersResponse\x12\x46\n\x0bGetUsersAll\x12\x19.users.UsersRequestStream\x1a\x1a.users.UsersResponseStream0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=22
  _globals['_USER']._serialized_end=54
  _globals['_USERREQUEST']._serialized_start=56
  _globals['_USERREQUEST']._serialized_end=81
  _globals['_USERRESPONSE']._serialized_start=83
  _globals['_USERRESPONSE']._serialized_end=124
  _globals['_USERSREQUEST']._serialized_start=126
  _globals['_USERSREQUEST']._serialized_end=152
  _globals['_USERSRESPONSE']._serialized_start=154
  _globals['_USERSRESPONSE']._serialized_end=196
  _globals['_USERSREQUESTSTREAM']._serialized_start=198
  _globals['_USERSREQUESTSTREAM']._serialized_end=218
  _globals['_USERSRESPONSESTREAM']._serialized_start=220
  _globals['_USERSRESPONSESTREAM']._serialized_end=268
  _globals['_USERS']._serialized_start=271
  _globals['_USERS']._serialized_end=457
# @@protoc_insertion_point(module_scope)
